# Generated by Django 4.2.16 on 2024-12-06 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='destinations',
            old_name='content',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='destinations',
            name='title',
        ),
        migrations.AddField(
            model_name='destinations',
            name='location',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='destinations',
            name='name',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
