# Generated by Django 4.2.16 on 2024-12-06 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0002_rename_content_destinations_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='destinations',
            options={'verbose_name': 'Destination'},
        ),
    ]
