# Generated by Django 4.2.16 on 2024-12-08 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0004_destination_delete_destinations'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='continent',
            field=models.CharField(choices=[('AF', 'Africa'), ('AN', 'Antarctica'), ('AS', 'Asia'), ('EU', 'Europe'), ('NA', 'North America'), ('OC', 'Oceania'), ('SA', 'South America')], default='Unknown', max_length=20),
        ),
        migrations.AddField(
            model_name='destination',
            name='country',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
