# Generated by Django 4.2.16 on 2024-12-10 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0006_recommendation'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendation',
            name='destination',
            field=models.ForeignKey(default=16, on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='destinations.destination'),
            preserve_default=False,
        ),
    ]
