# Generated by Django 4.2.16 on 2024-11-28 12:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0002_blogpost_content_blogpost_created_on_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPostComments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('approved', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('blogpost_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_post_comments', to='blog.blogpost')),
                ('comment_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_post_commenter', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
