# Generated by Django 4.2.16 on 2024-11-28 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blogpostcomments'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpostcomments',
            options={'verbose_name_plural': 'Blog Post Comments'},
        ),
    ]
